# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ff92c911603e11c86bc09f163a3bae2"
name = "kick-off"
application_url = "https://kick-off-three.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"

[access_scopes]
scopes = "write_products,write_themes"

[app_proxy]
url = "https://kick-off-three.vercel.app/apps/countdown"
subpath = "countdown"
prefix = "apps"

[auth]
redirect_urls = [
  "https://kick-off-three.vercel.app/auth/callback",
  "https://kick-off-three.vercel.app/api/auth"
]