// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/apps/countdown/analytics/track-click": {
    params: {};
  };
  "/apps/countdown/analytics/track-view": {
    params: {};
  };
  "/webhooks/app/subscriptions_update": {
    params: {};
  };
  "/api/bars/:barId/schedule-status": {
    params: {
      "barId": string;
    };
  };
  "/apps/countdown/email-submit": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/api/analytics/track-click": {
    params: {};
  };
  "/api/analytics/track-view": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/storefront/settings": {
    params: {};
  };
  "/apps/countdown/settings": {
    params: {};
  };
  "/api/cron/reset-views": {
    params: {};
  };
  "/api/billing/history": {
    params: {};
  };
  "/api/analytics/data": {
    params: {};
  };
  "/api/billing/create": {
    params: {};
  };
  "/api/billing/status": {
    params: {};
  };
  "/api/schedule/check": {
    params: {};
  };
  "/api/bars/active": {
    params: {};
  };
  "/api/geo/detect": {
    params: {};
  };
  "/api/settings": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/billing/confirm": {
    params: {};
  };
  "/app/bars/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/app/additional": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/templates": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/pricing": {
    params: {};
  };
  "/app/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/apps/countdown/analytics/track-click" | "/apps/countdown/analytics/track-view" | "/webhooks/app/subscriptions_update" | "/api/bars/:barId/schedule-status" | "/apps/countdown/email-submit" | "/webhooks/app/scopes_update" | "/api/analytics/track-click" | "/api/analytics/track-view" | "/webhooks/app/uninstalled" | "/api/storefront/settings" | "/apps/countdown/settings" | "/api/cron/reset-views" | "/api/billing/history" | "/api/analytics/data" | "/api/billing/create" | "/api/billing/status" | "/api/schedule/check" | "/api/bars/active" | "/api/geo/detect" | "/api/settings" | "/auth/login" | "/auth/*" | "/app" | "/app/billing/confirm" | "/app/bars/:id/edit" | "/app/additional" | "/app/analytics" | "/app/templates" | "/app/settings" | "/app/pricing" | "/app/new";
  };
  "routes/apps.countdown.analytics.track-click.jsx": {
    id: "routes/apps.countdown.analytics.track-click";
    page: "/apps/countdown/analytics/track-click";
  };
  "routes/apps.countdown.analytics.track-view.jsx": {
    id: "routes/apps.countdown.analytics.track-view";
    page: "/apps/countdown/analytics/track-view";
  };
  "routes/webhooks.app.subscriptions_update.jsx": {
    id: "routes/webhooks.app.subscriptions_update";
    page: "/webhooks/app/subscriptions_update";
  };
  "routes/api.bars.$barId.schedule-status.jsx": {
    id: "routes/api.bars.$barId.schedule-status";
    page: "/api/bars/:barId/schedule-status";
  };
  "routes/apps.countdown.email-submit.jsx": {
    id: "routes/apps.countdown.email-submit";
    page: "/apps/countdown/email-submit";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/api.analytics.track-click.jsx": {
    id: "routes/api.analytics.track-click";
    page: "/api/analytics/track-click";
  };
  "routes/api.analytics.track-view.jsx": {
    id: "routes/api.analytics.track-view";
    page: "/api/analytics/track-view";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.storefront.settings.jsx": {
    id: "routes/api.storefront.settings";
    page: "/api/storefront/settings";
  };
  "routes/apps.countdown.settings.jsx": {
    id: "routes/apps.countdown.settings";
    page: "/apps/countdown/settings";
  };
  "routes/api.cron.reset-views.jsx": {
    id: "routes/api.cron.reset-views";
    page: "/api/cron/reset-views";
  };
  "routes/api.billing.history.jsx": {
    id: "routes/api.billing.history";
    page: "/api/billing/history";
  };
  "routes/api.analytics.data.jsx": {
    id: "routes/api.analytics.data";
    page: "/api/analytics/data";
  };
  "routes/api.billing.create.jsx": {
    id: "routes/api.billing.create";
    page: "/api/billing/create";
  };
  "routes/api.billing.status.jsx": {
    id: "routes/api.billing.status";
    page: "/api/billing/status";
  };
  "routes/api.schedule.check.jsx": {
    id: "routes/api.schedule.check";
    page: "/api/schedule/check";
  };
  "routes/api.bars.active.jsx": {
    id: "routes/api.bars.active";
    page: "/api/bars/active";
  };
  "routes/api.geo.detect.jsx": {
    id: "routes/api.geo.detect";
    page: "/api/geo/detect";
  };
  "routes/api.settings.jsx": {
    id: "routes/api.settings";
    page: "/api/settings";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/billing/confirm" | "/app/bars/:id/edit" | "/app/additional" | "/app/analytics" | "/app/templates" | "/app/settings" | "/app/pricing" | "/app/new";
  };
  "routes/app.billing.confirm.jsx": {
    id: "routes/app.billing.confirm";
    page: "/app/billing/confirm";
  };
  "routes/app.bars.$id.edit.jsx": {
    id: "routes/app.bars.$id.edit";
    page: "/app/bars/:id/edit";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.analytics.jsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.templates.jsx": {
    id: "routes/app.templates";
    page: "/app/templates";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.pricing.jsx": {
    id: "routes/app.pricing";
    page: "/app/pricing";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.new.jsx": {
    id: "routes/app.new";
    page: "/app/new";
  };
};